### ISSUE TITLE
What is TRELLO_CONSUMER_KEY and where does it come from?

### ISSUE THREAD

**Issue by lastobelus** [ChrisYammine/ex_trello#18]
https://www.google.com/search?q=site:developers.trello.com+consumer+key:

No results found for site:developers.trello.com "consumer key".

[ruby-trello](https://github.com/jeremytregunna/ruby-trello) has a similar setup, so I assume you are both referring to somethin
g that no longer exists or is referred to differently in the current Trello documentation.

**Comment by yammine** [comment]
Hey @lastobelus ,
Looks like Trello let a few things fall through the cracks (on purpose I imagine) when rewriting their documentation & focusing on leading developers to create Power-Ups instead of vanilla third-party integrations. 

You can find your 'Consumer Key' and 'Consumer Secret' here: https://trello.com/app-key

Which should enable you to start an OAuth flow.

**Comment by lastobelus** [comment]
Thanks! I did actually eventually realize that's what was meant, but forgot to come close this.

**Comment by axelson** [comment]
Trello appears to have changed their key formats again. I'm only able to find/generate 3 keys now from the https://trello.com/app-key page

1. Developer API "Key"
  * Displayed directly on the page
2. Developer API "Token"
  * Generated by manually generating a "token"
3. Oauth "Secret"

But I'm not sure how to map those to the
```
config :ex_trello, :oauth, [
  consumer_key:    System.get_env("TRELLO_CONSUMER_KEY"),
  consumer_secret: System.get_env("TRELLO_CONSUMER_SECRET"),
  token:           System.get_env("TRELLO_ACCESS_TOKEN"),
  token_secret:    System.get_env("TRELLO_ACCESS_SECRET")
]
```

I have a partial PR ready to add some instructions to the README but I cannot figure out which keys I am missing.
